### PR TITLE
no more cw deps reexport

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by mina86** [comment]
What’s the repro for the benchmark failure?

**Comment by dzmitry-lahoda** [comment]
update picasso with latest cw vm and wait for ci to bench

**Comment by mina86** [comment]
Any repro that can be done manually.  To be honest, my jerk reaction to benchmark failing when this is set to 10000 is that the benchmark is wrong, i.e. it tests something that never happens.

**Comment by dzmitry-lahoda** [comment]
benchamrks  are substrate benchamrks on our parachain hosting cosmwasp pallet.

**Review by mina86 — APPROVED** [review]

**Pull request merged**
